[package]
name = "rust-rakitu-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.0"
ggrs = {version = "*"}
rand =  "0.8.5"